In [1]:
import sys
sys.path.extend(["../", ".", "../.."])
from nebula.pretraining import maskSequenceArr, maskSequence
from nebula import JSONTokenizer
import pickle
import numpy as np

import random
from copy import deepcopy


vocabPath = r"C:\Users\dtrizna\Code\nebula\data\data_filtered\speakeasy_trainset\speakeasy_VocabSize_1500.pkl"

with open(vocabPath, "rb") as f:
    vocab = pickle.load(f)

tokenizer = JSONTokenizer()
tokenizer.loadVocab(vocab)

x_train = r"C:\Users\dtrizna\Code\nebula\data\data_filtered\speakeasy_trainset\speakeasy_VocabSize_1500_maxLen_2048.npy"
x_train = np.load(x_train)


In [2]:
sequence = x_train[0]

maskedSequenceList, whereMaskedList, maskedTokenIdsList = maskSequence(sequence, vocab, mask_probability=0.15, random_state=43, token_id_type="onehot")
maskedSequenceArr, whereMaskedArr, maskedTokenIdsArr = maskSequenceArr(sequence, vocab, mask_probability=0.15, random_state=43, token_id_type="onehot")


In [3]:
print(whereMaskedArr[5:15])
print(maskedSequenceArr[5:15])
print(maskedTokenIdsArr[0:20])

[0 0 0 1 0 0 0 0 1 0]
[ 62   3  38   2  79   4  68   3 319   4]
[0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1]


In [4]:
print(whereMaskedList[5:15])
print(maskedSequenceList[5:15])
print(maskedTokenIdsList[0:20])

[0 0 0 1 0 0 0 0 1 0]
[62  3 38  2 79  4 68  3  2  4]
[0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1]


In [10]:
maskedSequenceArr[0:20]

array([319,  91, 319,  93,   3,  62,   3,  38,   2,  79,   4,  68,   3,
       319,   4, 149, 153,  32,   2,   5])

In [11]:
# compare with numpy if arr1 is equal to arr2
print(np.array_equal(maskedSequenceArr, maskedSequenceList))

# show differences
np.where(maskedSequenceArr != maskedSequenceList)

False


(array([  0,   2,  13,  30,  38, 145, 149, 154, 182, 198, 206, 218, 240,
        245, 248, 263, 277, 296, 304, 313, 324, 366, 367, 373, 418, 438,
        448, 459, 516, 520, 553, 597, 606, 612, 614, 629, 643, 652, 677,
        715, 717, 774, 785, 847, 881, 955, 977], dtype=int64),)

In [12]:
sequence[0:5]

array([45, 91,  3, 93,  3])

In [13]:
maskedSequenceArr[0:5]

array([319,  91, 319,  93,   3])

In [14]:
maskedSequenceList[0:5]

array([368,  91,   3,  93,   3])